line1='              OPTISIS          ';
line2='              NEW MENU         ';
line3='              ALT MENU         ';
line4='              OPTIONS          ';
line5='              CREDITS          ';
line6='              PROJECT          ';
line7='                 RAM           ';
line8='            TRANSMITTER        ';
fid = fopen('text_file.txt','w');
fprintf(fid,'x"%X",',line1);
fprintf(fid,'x"0D",');
fprintf(fid,'\n');
fprintf(fid,'x"%X",',line2);
fprintf(fid,'x"0D",');
fprintf(fid,'\n');
fprintf(fid,'x"%X",',line3);
fprintf(fid,'x"0D",');
fprintf(fid,'\n');
fprintf(fid,'x"%X",',line4);
fprintf(fid,'x"0D",');
fprintf(fid,'\n');
fprintf(fid,'x"%X",',line5);
fprintf(fid,'x"0D",');
fprintf(fid,'\n');
fprintf(fid,'x"%X",',line6);
fprintf(fid,'x"0D",');
fprintf(fid,'\n');
fprintf(fid,'x"%X",',line7);
fprintf(fid,'x"0D",');
fprintf(fid,'\n');
fprintf(fid,'x"%X",',line8);
fprintf(fid,'x"0D",');
fclose(fid);

